from django.contrib import admin
from django.urls import path
from managment import views

urlpatterns = [
    path('',  views.Index_page, name="Index_page"),
    path('Home_page', views.Home_page, name="Home_page"),
    path('Courses_page', views.Courses_page, name="Courses_page"),
    path('Faculty_page', views.Faculty_page, name="Faculty_page"),
    path('About_page', views.About_page, name="About_page"),
    path('Contact_page', views.Contact_page, name="Contact_page"),
    path('Student_login',  views.Student_login, name="Student_login"),
    path('Student_register', views.Student_register, name="Student_register"),
    path('Data_register',views.Data_register,name="Data_register"),
    path('Data_login',views.Data_login,name="Data_login"),
    path('Student_home',views.Student_home,name="Student_home"),
    path('Student_registration',views.Student_registration,name="Student_registration"),
    path('Student_profile', views.Student_profile, name="Student_profile"),
    path('Student_mstresult', views.Student_mstresult, name="Student_mstresult"),
    path('Student_registration_form', views.Student_registration_form, name="Student_registration_form"),
    path('Update_student_profile<id>', views.Update_student_profile, name="Update_student_profile"),
    path('logout',  views.logout, name="logout"),
    path('Faculty_logout',  views.Faculty_logout, name="Faculty_logout"),
    path('Your_registration', views.Your_registration, name="Your_registration"),
    path('Update_registration_form<id>', views.Update_registration_form, name="Update_registration_form"),
   path('Faculty_login',  views.Faculty_login, name="Faculty_login"),
    path('Faculty_home',  views.Faculty_home, name="Faculty_home"),
    path('Faculty_data_login',views.Faculty_data_login,name="Faculty_data_login"),
    path('Faculty_profile',  views.Faculty_profile, name="Faculty_profile"),
    path('Update_faculty_profile<id>', views.Update_faculty_profile, name="Update_faculty_profile"),
    path('Show_student_registration_form',  views.Show_student_registration_form, name="Show_student_registration_form"),
    path('Show_student_registration_formm',  views.Show_student_registration_formm, name="Show_student_registration_formm"),
    path('view_mst_details<mst>', views.view_mst_details, name="view_mst_details"),
    path('No_dues',  views.No_dues, name="No_dues"),
    path('Add_student',  views.Add_student, name="Add_student"),
    path('Add_MST_Marks',  views.Add_MST_Marks, name="Add_MST_Marks"),
    path('Check_no_Dues',  views.Check_no_Dues, name="Check_no_Dues"),
    path('Do_add_student',  views.do_add_student, name="do_add_student"),
    path('Do_add_mst_marks',  views.do_add_mst_marks, name="do_add_mst_marks"),
    path('View_MST_Marks',  views.View_MST_Marks, name="View_MST_Marks"),
    path('View_MST_Markss',  views.View_MST_Markss, name="View_MST_Markss"),
    path('Delete_student', views.delete_student, name="delete_student"),
    path('Update_student<id>', views.update_student, name="update_student"),
    path('Do_update_mst_marks<id>',  views.do_update_mst_marks, name="do_update_mst_marks"),
    path('View_add_student', views.View_add_student, name="View_add_student"),
    path('View_add_studentt', views.View_add_studentt, name="View_add_studentt"),
    path('Delete_added_student', views.delete_added_student, name="delete_added_student"),
    path('Update_added_student<id>', views.update_added_student, name="update_added_student"),
    path('Do_update_added_student<id>', views.do_update_added_student, name="do_update_added_student"),
    path('Contact_View', views.Contact_View, name="Contact_View"),
path('Forget_password', views.forget_password, name="forget_password"),
    path('Do_Forget_password', views.do_forget_password, name="do_forget_password"),
    path('Enter_Otp', views.enter_otp, name="enter_otp"),
    path('Do_new_password', views.do_new_password, name="do_new_password"),
    path('complete_status', views.complete_status, name="complete_status"),
    path('checkout', views.checkout, name="checkout"),
path('Student_attendence', views.Student_attendence, name="Student_attendence"),
path('do_Student_attendence', views.do_Student_attendence, name="do_Student_attendence"),
path('Absent', views.absent, name="absent"),
path('Present', views.present, name="present"),
    path('Resend_otp<email>', views.Resend_otp, name="Resend_otp"),
path('Your_attendence', views.Your_attendence, name="Your_attendence"),
path('Send_pending_email', views.Send_pending_email, name="Send_pending_email"),
path('Send_success_email', views.Send_success_email, name="Send_success_email"),
    path('handlerequest/', views.handlerequest, name="handlerequest"),
path('transactions', views.transactions, name="transactions"),

]
