# Generated by Django 3.1.6 on 2021-02-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(default='null', max_length=50)),
                ('faculty_name', models.CharField(max_length=30)),
                ('faculty_password', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('Bachelor_of_Engineering', 'Bachelor_of_Engineering'), ('Bachelor_of_Pharmacy', 'Bachelor_of_Pharmacy'), ('Bachelor_of_Technology', 'Bachelor_of_Technology'), ('Industrial_Training_Institute', 'Industrial_Training_Institute'), ('Diploma', 'Diploma'), ('Master_Of_Administration', 'Master_Of_Administration'), ('Master_Of_Technology', 'Master_Of_Technology'), ('Master_of_Engineering', 'Master_of_Engineering')], max_length=30)),
                ('faculty_number', models.CharField(default='null', max_length=50)),
                ('faculty_email', models.EmailField(default='null', max_length=50)),
                ('photo', models.ImageField(upload_to='media/faculty_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='MST_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=30)),
                ('mst', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('marks_obtained', models.CharField(max_length=30)),
                ('total_marks', models.CharField(max_length=30)),
                ('faculty_id', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=30)),
                ('enrollment_number', models.CharField(default='null', max_length=30)),
                ('branch', models.CharField(choices=[('Bachelor_of_Engineering', 'Bachelor_of_Engineering'), ('Bachelor_of_Pharmacy', 'Bachelor_of_Pharmacy'), ('Bachelor_of_Technology', 'Bachelor_of_Technology'), ('Industrial_Training_Institute', 'Industrial_Training_Institute'), ('Diploma', 'Diploma'), ('Master_Of_Administration', 'Master_Of_Administration'), ('Master_Of_Technology', 'Master_Of_Technology'), ('Master_of_Engineering', 'Master_of_Engineering')], default='null', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('enrollment_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Semester_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=10)),
                ('enrollment_number', models.CharField(max_length=12)),
                ('father_name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=30)),
                ('semester', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=200)),
                ('photo', models.ImageField(upload_to='media/Student_registration_photo/')),
                ('signature', models.ImageField(upload_to='media/Student_registration_signature/')),
            ],
        ),
    ]
