# Generated by Django 3.1.6 on 2021-02-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mst_result',
            name='faculty_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_all',
            name='branch',
            field=models.CharField(choices=[('Bachelor_of_Engineering', 'Bachelor_of_Engineering'), ('Bachelor_of_Pharmacy', 'Bachelor_of_Pharmacy'), ('Bachelor_of_Technology', 'Bachelor_of_Technology'), ('Industrial_Training_Institute', 'Industrial_Training_Institute'), ('Diploma', 'Diploma'), ('Master_Of_Administration', 'Master_Of_Administration'), ('Master_Of_Technology', 'Master_Of_Technology'), ('Master_of_Engineering', 'Master_of_Engineering')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student_all',
            name='enrollment_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_all',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
