# Generated by Django 3.1.6 on 2021-02-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_auto_20210216_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_all',
            name='branch',
            field=models.CharField(max_length=30),
        ),
    ]
