# Generated by Django 3.1.6 on 2021-02-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
