# Generated by Django 3.1.6 on 2021-02-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0006_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(blank=True, choices=[('Faculty', 'Faculty'), ('HOD', 'HOD')], max_length=30),
        ),
    ]
