# Generated by Django 3.1.6 on 2021-02-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0009_auto_20210227_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_all',
            old_name='previous_panding',
            new_name='previous_pending',
        ),
        migrations.RenameField(
            model_name='student_all',
            old_name='total_panding',
            new_name='total_pending',
        ),
    ]
