# Generated by Django 3.1.6 on 2021-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0010_auto_20210227_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('attendance', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student_semester_register',
            name='photo',
            field=models.ImageField(default='media/person1.jpg', upload_to='media/Student_registration_photo/'),
        ),
    ]
