# Generated by Django 3.1.6 on 2021-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0012_auto_20210310_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_all',
            name='branch',
            field=models.CharField(blank=True, choices=[('Mechanical_Engineering_(BE)', 'Mechanical_Engineering_(BE)'), ('Civil_Engineering_(BE)', 'Civil_Engineering_(BE)'), ('Computer_Science_Engineering_(BE)', 'Computer_Science_Engineering_(BE)'), ('Computer_Science_Engineering_(BE)', 'Computer_Science_Engineering_(BE)'), ('Electrical_Engineering_(BE)', 'Electrical_Engineering_(BE)'), ('Electronics_&_Comunication_Engineering_(BE)', 'Electronics_&_Comunication_Engineering_(BE)'), ('Mechanical_Engineering_(B Tech)', 'Mechanical_Engineering_(B Tech)'), ('Civil_Engineering_(B Tech)', 'Civil_Engineering_(B Tech)'), ('Computer_Science_Engineering_(B Tech)', 'Computer_Science_Engineering_(B Tech)'), ('Electrical_Engineering_(B Tech)', 'Electrical_Engineering_(B Tech)'), ('Electronics_&_Comunication_Engineering_(B Tech)', 'Electronics_&_Comunication_Engineering_(B Tech)'), ('Mechanical_Engineering_(M Tech)', ''), ('Civil_Engineering_(M Tech)', 'Civil_Engineering_(M Tech)'), ('Computer_Science_Engineering_(M Tech)', 'Computer_Science_Engineering_(M Tech)'), ('Electrical_Engineering_(M Tech)', 'Electrical_Engineering_(M Tech)'), ('Electronics_&_Comunication_Engineering_(M Tech)', 'Electronics_&_Comunication_Engineering_(M Tech)'), ('Human_Resources_Mangement_(MBA)', 'Human_Resources_Mangement_(MBA)'), ('Financial_Management_(MBA)', 'Financial_Management_(MBA)'), ('Systems_Management_(MBA)', 'Systems_Management_(MBA)'), ('Mechanical_Engineering_(Diploma)', 'Mechanical_Engineering_(Diploma)'), ('Electrical_Engineering_(Diploma)', 'Electrical_Engineering_(Diploma)'), ('Electronics_and_Communication (Diploma)', 'Electronics_and_Communication (Diploma)'), ('Civil_Engineering_(Diploma)', 'Civil_Engineering_(Diploma)'), ('Computer_Science_and_Engineering_(Diploma)', 'Computer_Science_and_Engineering_(Diploma)'), ('IT_Engineering_(Diploma)', 'IT_Engineering_(Diploma)'), ('Chemical_Engineering_(Diploma)', 'Chemical_Engineering_(Diploma)'), ('Mechanical_Engineering_(ITI)', 'Mechanical_Engineering_(ITI)'), ('Tool_&_Die_Maker_Engineering_(ITI)', 'Tool_&_Die_Maker_Engineering_(ITI)'), ('Pump_Operator_(ITI)', 'Pump_Operator_(ITI)'), ('Civil_Engineering_(ITI )', 'Civil_Engineering_(ITI )'), ('Fitter_Engineering_(ITI)', 'Fitter_Engineering_(ITI)'), ('Computer_Engineering_(ITI)', 'Computer_Engineering_(ITI)'), ('Turner_Engineering_(ITI)', 'Turner_Engineering_(ITI)'), ('Bechelor_in_Pharmacy', 'Bechelor_in_Pharmacy'), ('Master_in_Pharmacy', 'Master_in_Pharmacy')], max_length=100),
        ),
    ]
