# Generated by Django 3.1.6 on 2021-03-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0013_auto_20210311_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
