# Generated by Django 3.2 on 2021-05-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0015_auto_20210420_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='txn_details',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='txn_details',
            name='enrollment_number',
            field=models.CharField(default='000', max_length=200),
        ),
        migrations.AddField(
            model_name='txn_details',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='txn_details',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='txn_details',
            name='txndate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='txn_details',
            name='txnid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
