# Generated by Django 3.2 on 2021-05-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0016_auto_20210501_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txn_details',
            name='enrollment_number',
            field=models.CharField(max_length=200),
        ),
    ]
